language: python
python:
- '2.7'
env:
- DJANGO=django==1.8.*
- DJANGO=django==1.11.*
install:
- pip install $DJANGO
- pip install coveralls
- pip install -r test_requirements.txt
- python setup.py install
script: python manage.py test
notifications:
  email: false
deploy:
  provider: pypi
  user: deep-c
  password:
    secure: B8zmLAPxlzmwUNSJa6JOik/IO+/i/fsrCoasjcS0ogl83C/WCde0yPeXGtLVg7XhhCjm0P85icS3oHDGu+XOUYv9a9vfCf9C2gofgqekav4MeXNnJ+FKMvm/xWmVJsWRqLEFd4FLkC5Ei1tlys2uTCpM0PyioFAgP4G4YbOVI1ZZHYQoXVEsY1levlxXFWPwErvlboxolE3B/i9wS32YUL0oKIl1WC04XN5XknEvgRY2aNat8+9CDEfnLDGSYLwLFr+UCjqE5ilZeuyE++3un0hxLvys+IFWhc5tNEq3K54QtzFQGCZd2Dx5Fz9gvWSfUVsoho047iWddhPORSBjlN4gFaVXKWYxPXniXQ+DmA5x43ElyEhfXWHS7xWwonkpX1z0Pp2niFLDsoQItBvPmwVSRhVbdM6lRvBXEzvWQbHqGEPrPXZGX/93WQGfTWSMDqgN08ZAlf8jkCJm5qwXym05+ofOik0/EqCa3BLigHfvDGjtnv4iagj+u33NKnP0prAo0Li70Ff5A0Evtp9YV+P8PuHWV6J7gNjeEsNMlNGR8o7uzCPbc2WmBtSlCbrDh1xBvLXCEpfqoUvfWyo3KykGj7f1rHOemgG98sON1G1fUQAJZLHUkV5fvouxoXcXzJs2xY7pHAl/H7lDVfedqeriwBHOoNdvJeDJAk8vixw=
  on:
    tags: true
    branch: master
after_success:
- coveralls
