language: python
python:
- '2.7'
env:
- DJANGO=django==1.8.*
- DJANGO=django==1.11.*
install:
- pip install $DJANGO
- pip install coveralls
- pip install -r test_requirements.txt
- python setup.py install
script: python manage.py test
notifications:
  email: false
deploy:
  provider: pypi
  user: deep-c
  password:
    secure: cBcxZ1m/CL69+bbEaOJxdHImIcLRCRlsK1uiQvXfPss/E4hve07rH+272eHuctmajrzeTn10pUWGm5k7Yd2i+n+gs6IG71l8b24xn+EkZdfQ0xBJnhZnTy0hSV1ppplJL+Mey/zf4UNEKzVoNMzOz2c3MpSV/Yce2srgAaFuwagfcsOi7xgq0v2z1xim0MspJAd0IpO+r36TY1Est1wvoq6QcQEU9k+Y9LyJuM8ZCp/6plz3vMY3ZV+PdKDP4aDja08FSE57yGkc7qGSOrTew/Jy3XV7WekmYTCVM40XuLJYEfV2RSbIsyokNUk9TNRrW+DI/8MUcuUYgcD5pBFLORQJEd/ijVnlirhn6eehGNQShxiO98PsgeChoOtL7LzOKka4cxzXFMprSmeaTV5P5l8PfjPj5RU1+J4i83BxEfDwPPKHMY2gBrT15g1uFDIfP99/YN5FwXg3eK/Tn5WDVRmYfUCdBdFlVtCWDSetBn3WFFnntziG5B93EABBIMBvtCzQ/8nhgkXl1yKszwDYwNnETRHB0V0NpucR8HqKnBkSxdM0MQpeFi1eiMCfmLg4bHEKnF8GA+GysvhW/yQ+QAR2j+BUMlvUN58aWhKBGdBAkLgQawESl3rvAtw+L3763XZ2CvmCXER9FKNlFQVYVKidKBrlgblTFNE46FIH+Rc=
  on:
    tags: true
    branch: master
after_success:
- coveralls
