language: python
python:
- '2.7'
env:
- DJANGO=django==1.8.*
- DJANGO=django==1.11.*
install:
- pip install $DJANGO
- pip install coveralls
- pip install -r test_requirements.txt
- python setup.py install
script: python manage.py test
notifications:
  email: false
deploy:
  provider: pypi
  user: deep-c
  password:
    secure: TYEzPLSKhbiOn1JTkPGllWSLmgTEaOsDHbSOxnrUK05Ijd6CV+1yIL/srCltpxmngzH7f/erjuxlbry/9CqNpd6TF8LKdOFnvyQuBlRHky+2d92SHpFiAjwI/MjNH5f8hCtEnxFKNPhDzywYhcT6Bw2GaiyaRzDl5XRDwqRiKXu91PLDtZo/peaQDsij3KWRHRit6YbEP4ffhG3hhz67yeqG2oGPUOg7zMe8myqMNwYWxdd38Rh5ovUvvX+FWYKk4YoyiQ1Z+QQCoCGQSF6y6O7ouqVGQ1+KfQtMxdjyfNDQcM2PrE3mK+5Cu/870mZBey7TfDEW7IV3awccXri8xavxftuHMZktmqSfrK3T2ERqSztVBMVaNZl4XLjdFd1Wc4e8vFbYgCs4lWTsFyML0Lb69tIfTuJ60K8M0KDKplCtQpEwaXEilWW7HVzGqMJkNNloRGeLsnhK9xpTjqWxBsqkdCXzJFN3tfaDWDtEQz7ys/6SShES39KIV1Qc69TdEsCaIIShCp5+fv9jJe2kvlt7h+4JMccDUsebZ2VJg4b1YszPWUaMMToYGIYVv5qNHUMFmq0ZRL+hyBkD5IE6WowCzJwDC9uXOXamWsWR6l5YYhKPiw08Ll4t01WybrGp2DyirYY9kDYVfflLfH8PRVV8vG1QR5/9eRrV5sUy1dw=
  on:
    tags: true
    branch: master
after_success:
- coveralls
